import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Button } from "../stories/Button";
export default function Home(props: { label: string }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Button label={props.label} color="primary" size="large"></Button>
      </main>
    </div>
  );
}

export const getStaticProps = () => {
  return {
    props: { label: "test button" }, // will be passed to the page component as props
  };
};
